/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\JinYun\\Desktop\\项目\\demo\\pengBlog\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f95dba00",
    path: "/blogs/category1/2018/20180107.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f95dba00").then(next)
    },
  },
  {
    name: "v-21d6474e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21d6474e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3f6211c0",
    path: "/blogs/category1/2018/20180612.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f6211c0").then(next)
    },
  },
  {
    name: "v-17ae3340",
    path: "/blogs/category1/2018/20180816.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17ae3340").then(next)
    },
  },
  {
    name: "v-7f215b00",
    path: "/blogs/category1/2018/20180921.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f215b00").then(next)
    },
  },
  {
    name: "v-b4672840",
    path: "/blogs/category1/2018/20180122.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b4672840").then(next)
    },
  },
  {
    name: "v-4e013100",
    path: "/blogs/category1/2018/20180213.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e013100").then(next)
    },
  },
  {
    name: "v-fb822f80",
    path: "/blogs/category1/2018/20181021.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb822f80").then(next)
    },
  },
  {
    name: "v-bee86fc0",
    path: "/blogs/category1/2018/20181220.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bee86fc0").then(next)
    },
  },
  {
    name: "v-951c3840",
    path: "/blogs/category1/2018/20181112.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-951c3840").then(next)
    },
  },
  {
    name: "v-0a14ab60",
    path: "/blogs/category1/2018/20181215.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a14ab60").then(next)
    },
  },
  {
    name: "v-1aced800",
    path: "/blogs/category1/2019/20190330.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1aced800").then(next)
    },
  },
  {
    name: "v-b35c79c0",
    path: "/blogs/category1/2019/20190216.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b35c79c0").then(next)
    },
  },
  {
    name: "v-af2e10c0",
    path: "/blogs/category1/2019/20190124.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af2e10c0").then(next)
    },
  },
  {
    name: "v-1efd4100",
    path: "/blogs/category1/2019/20190422.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1efd4100").then(next)
    },
  },
  {
    name: "v-a08ef180",
    path: "/blogs/category1/2019/20190523.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a08ef180").then(next)
    },
  },
  {
    name: "v-774b6b20",
    path: "/blogs/category1/2019/20190711.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-774b6b20").then(next)
    },
  },
  {
    name: "v-4cf7e180",
    path: "/blogs/category1/2019/20190622.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4cf7e180").then(next)
    },
  },
  {
    name: "v-f6491800",
    path: "/blogs/category1/2019/20191023.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f6491800").then(next)
    },
  },
  {
    name: "v-275b7200",
    path: "/blogs/category1/2019/20190921.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-275b7200").then(next)
    },
  },
  {
    name: "v-ce953980",
    path: "/blogs/category1/2019/20191227.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ce953980").then(next)
    },
  },
  {
    name: "v-193b5c40",
    path: "/blogs/category1/2019/20191120.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-193b5c40").then(next)
    },
  },
  {
    name: "v-636b3320",
    path: "/blogs/category1/2019/20191228.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-636b3320").then(next)
    },
  },
  {
    name: "v-e9c008c0",
    path: "/blogs/category1/2019/20191202.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e9c008c0").then(next)
    },
  },
  {
    name: "v-5d2947a0",
    path: "/blogs/category1/2020/20200102.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d2947a0").then(next)
    },
  },
  {
    name: "v-44a268c0",
    path: "/blogs/category1/2020/20200212.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44a268c0").then(next)
    },
  },
  {
    name: "v-05f13a00",
    path: "/blogs/category1/2020/20200316.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05f13a00").then(next)
    },
  },
  {
    name: "v-9e803ac0",
    path: "/blogs/category1/2020/20200517.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e803ac0").then(next)
    },
  },
  {
    name: "v-71028760",
    path: "/blogs/category1/2020/20200621.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71028760").then(next)
    },
  },
  {
    name: "v-52b5a780",
    path: "/blogs/category1/2020/20200422.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52b5a780").then(next)
    },
  },
  {
    name: "v-b794fa00",
    path: "/blogs/category1/2020/20200712.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b794fa00").then(next)
    },
  },
  {
    name: "v-0a210200",
    path: "/blogs/category1/2020/20200723.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a210200").then(next)
    },
  },
  {
    name: "v-24bb0700",
    path: "/blogs/category1/2020/20200822.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24bb0700").then(next)
    },
  },
  {
    name: "v-fa757bc0",
    path: "/blogs/category1/2020/20200917.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa757bc0").then(next)
    },
  },
  {
    name: "v-31e08800",
    path: "/blogs/category1/2020/20201023.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31e08800").then(next)
    },
  },
  {
    name: "v-182b8320",
    path: "/blogs/category1/2020/20201206.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-182b8320").then(next)
    },
  },
  {
    name: "v-565e5fc0",
    path: "/blogs/category1/2021/20210112.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-565e5fc0").then(next)
    },
  },
  {
    name: "v-0773d060",
    path: "/blogs/category1/2020/20201130.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0773d060").then(next)
    },
  },
  {
    name: "v-055c9be0",
    path: "/blogs/category1/2020/20201222.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-055c9be0").then(next)
    },
  },
  {
    name: "v-0f7de0ad",
    path: "/docs/Nuxt/asyncData.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f7de0ad").then(next)
    },
  },
  {
    name: "v-01bb2340",
    path: "/blogs/category1/2021/20210226.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01bb2340").then(next)
    },
  },
  {
    name: "v-01748fb5",
    path: "/docs/Nuxt/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01748fb5").then(next)
    },
  },
  {
    name: "v-23b9ead9",
    path: "/docs/Vue/API.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23b9ead9").then(next)
    },
  },
  {
    name: "v-3b3ae840",
    path: "/blogs/category1/2021/20210122.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b3ae840").then(next)
    },
  },
  {
    name: "v-73f27207",
    path: "/docs/Vue/Data.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73f27207").then(next)
    },
  },
  {
    name: "v-16a30127",
    path: "/docs/Vue/asyncComponent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16a30127").then(next)
    },
  },
  {
    name: "v-45a4bc0d",
    path: "/docs/Nuxt/context.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45a4bc0d").then(next)
    },
  },
  {
    name: "v-1ad07d56",
    path: "/docs/Vue/attribute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ad07d56").then(next)
    },
  },
  {
    name: "v-7b37f5f2",
    path: "/docs/Vue/animationClass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b37f5f2").then(next)
    },
  },
  {
    name: "v-c63ab422",
    path: "/docs/Vue/directive.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c63ab422").then(next)
    },
  },
  {
    name: "v-0d2706d9",
    path: "/docs/Vue/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d2706d9").then(next)
    },
  },
  {
    name: "v-63d8ae87",
    path: "/docs/Vue/funComponent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63d8ae87").then(next)
    },
  },
  {
    name: "v-1db6f6e7",
    path: "/docs/Vue/ref.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1db6f6e7").then(next)
    },
  },
  {
    name: "v-9f5475d2",
    path: "/docs/Vue/filters.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f5475d2").then(next)
    },
  },
  {
    name: "v-18ea60f2",
    path: "/docs/Vue/template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18ea60f2").then(next)
    },
  },
  {
    name: "v-548658f2",
    path: "/docs/Vue/slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-548658f2").then(next)
    },
  },
  {
    name: "v-d1cc67f2",
    path: "/docs/Vue/v-if&v-for.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1cc67f2").then(next)
    },
  },
  {
    name: "v-5abaae7b",
    path: "/docs/Vue/renderFun.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5abaae7b").then(next)
    },
  },
  {
    name: "v-16d28407",
    path: "/docs/Vue/v-bind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16d28407").then(next)
    },
  },
  {
    name: "v-4dfc2596",
    path: "/docs/delicacys/%E6%97%A0%E6%B2%B9%E6%8D%9E%E6%B1%81%E7%B2%89%E4%B8%9D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dfc2596").then(next)
    },
  },
  {
    path: "/docs/delicacys/无油捞汁粉丝.html",
    redirect: "/docs/delicacys/%E6%97%A0%E6%B2%B9%E6%8D%9E%E6%B1%81%E7%B2%89%E4%B8%9D.html"
  },
  {
    name: "v-18f77d29",
    path: "/docs/Vue/v-model.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18f77d29").then(next)
    },
  },
  {
    name: "v-0e73ed27",
    path: "/docs/Vue/v-is.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e73ed27").then(next)
    },
  },
  {
    name: "v-25cf21cd",
    path: "/docs/jottings/DOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25cf21cd").then(next)
    },
  },
  {
    name: "v-a834b066",
    path: "/docs/jottings/Git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a834b066").then(next)
    },
  },
  {
    name: "v-036cff0d",
    path: "/docs/jottings/BOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-036cff0d").then(next)
    },
  },
  {
    name: "v-0cc8b28d",
    path: "/docs/jottings/HarmonyOS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cc8b28d").then(next)
    },
  },
  {
    name: "v-7c41320d",
    path: "/docs/jottings/Nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c41320d").then(next)
    },
  },
  {
    name: "v-c019ed66",
    path: "/docs/jottings/accordion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c019ed66").then(next)
    },
  },
  {
    name: "v-c80c1626",
    path: "/docs/jottings/genealogy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c80c1626").then(next)
    },
  },
  {
    name: "v-40b05a4d",
    path: "/docs/jottings/flexbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40b05a4d").then(next)
    },
  },
  {
    name: "v-5872dd42",
    path: "/docs/jottings/filter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5872dd42").then(next)
    },
  },
  {
    name: "v-4258630d",
    path: "/docs/jottings/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4258630d").then(next)
    },
  },
  {
    name: "v-85606726",
    path: "/docs/jottings/particles.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85606726").then(next)
    },
  },
  {
    name: "v-bcaea4a6",
    path: "/docs/jottings/reset.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bcaea4a6").then(next)
    },
  },
  {
    name: "v-5248d10d",
    path: "/docs/jottings/scrollTemp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5248d10d").then(next)
    },
  },
  {
    name: "v-83700cea",
    path: "/docs/jottings/mobile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-83700cea").then(next)
    },
  },
  {
    name: "v-dea57fe2",
    path: "/docs/jottings/shadow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dea57fe2").then(next)
    },
  },
  {
    name: "v-763b410d",
    path: "/docs/jottings/whirligig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-763b410d").then(next)
    },
  },
  {
    name: "v-dabf3b02",
    path: "/docs/jottings/vueBuild.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dabf3b02").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-dab8e1c2",
    path: "/tag/Nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dab8e1c2").then(next)
    },
    meta: {"pid":"tags","id":"Nginx"}
  },
  {
    path: "/tag/Nginx/index.html",
    redirect: "/tag/Nginx/"
  },
  {
    name: "v-e8d965c8",
    path: "/tag/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d965c8").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/index.html",
    redirect: "/tag/JS/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-ec38e77e",
    path: "/tag/Cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-ec38e77e").then(next)
    },
    meta: {"pid":"tags","id":"Cookie"}
  },
  {
    path: "/tag/Cookie/index.html",
    redirect: "/tag/Cookie/"
  },
  {
    name: "v-3248559a",
    path: "/tag/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3248559a").then(next)
    },
    meta: {"pid":"tags","id":"VUE"}
  },
  {
    path: "/tag/VUE/index.html",
    redirect: "/tag/VUE/"
  },
  {
    name: "v-7c44ce15",
    path: "/tag/运算符/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7c44ce15").then(next)
    },
    meta: {"pid":"tags","id":"运算符"}
  },
  {
    path: "/tag/运算符/index.html",
    redirect: "/tag/运算符/"
  },
  {
    path: "/tag/%E8%BF%90%E7%AE%97%E7%AC%A6/",
    redirect: "/tag/运算符/"
  },
  {
    name: "v-3231af64",
    path: "/tag/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3231af64").then(next)
    },
    meta: {"pid":"tags","id":"npm"}
  },
  {
    path: "/tag/npm/index.html",
    redirect: "/tag/npm/"
  },
  {
    name: "v-4bc4e1e0",
    path: "/tag/组件/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4bc4e1e0").then(next)
    },
    meta: {"pid":"tags","id":"组件"}
  },
  {
    path: "/tag/组件/index.html",
    redirect: "/tag/组件/"
  },
  {
    path: "/tag/%E7%BB%84%E4%BB%B6/",
    redirect: "/tag/组件/"
  },
  {
    name: "v-0c1cbc56",
    path: "/tag/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0c1cbc56").then(next)
    },
    meta: {"pid":"tags","id":"正则"}
  },
  {
    path: "/tag/正则/index.html",
    redirect: "/tag/正则/"
  },
  {
    path: "/tag/%E6%AD%A3%E5%88%99/",
    redirect: "/tag/正则/"
  },
  {
    name: "v-1f2f3733",
    path: "/categories/问题集中营/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-1f2f3733").then(next)
    },
    meta: {"pid":"categories","id":"问题集中营"}
  },
  {
    path: "/categories/问题集中营/index.html",
    redirect: "/categories/问题集中营/"
  },
  {
    path: "/categories/%E9%97%AE%E9%A2%98%E9%9B%86%E4%B8%AD%E8%90%A5/",
    redirect: "/categories/问题集中营/"
  },
  {
    name: "v-d2055fbe",
    path: "/categories/前端小笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d2055fbe").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/index.html",
    redirect: "/categories/前端小笔记/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
    redirect: "/categories/前端小笔记/"
  },
  {
    name: "v-d0fbe166",
    path: "/categories/Cookie/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d0fbe166").then(next)
    },
    meta: {"pid":"categories","id":"Cookie"}
  },
  {
    path: "/categories/Cookie/index.html",
    redirect: "/categories/Cookie/"
  },
  {
    name: "v-85672be2",
    path: "/categories/排序/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-85672be2").then(next)
    },
    meta: {"pid":"categories","id":"排序"}
  },
  {
    path: "/categories/排序/index.html",
    redirect: "/categories/排序/"
  },
  {
    path: "/categories/%E6%8E%92%E5%BA%8F/",
    redirect: "/categories/排序/"
  },
  {
    name: "v-7f070da7",
    path: "/categories/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f070da7").then(next)
    },
    meta: {"pid":"categories","id":"VUE"}
  },
  {
    path: "/categories/VUE/index.html",
    redirect: "/categories/VUE/"
  },
  {
    name: "v-3dfe3db2",
    path: "/categories/Promise/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3dfe3db2").then(next)
    },
    meta: {"pid":"categories","id":"Promise"}
  },
  {
    path: "/categories/Promise/index.html",
    redirect: "/categories/Promise/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-7f1260c2",
    path: "/categories/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f1260c2").then(next)
    },
    meta: {"pid":"categories","id":"npm"}
  },
  {
    path: "/categories/npm/index.html",
    redirect: "/categories/npm/"
  },
  {
    name: "v-b5983fc8",
    path: "/categories/组件/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-b5983fc8").then(next)
    },
    meta: {"pid":"categories","id":"组件"}
  },
  {
    path: "/categories/组件/index.html",
    redirect: "/categories/组件/"
  },
  {
    path: "/categories/%E7%BB%84%E4%BB%B6/",
    redirect: "/categories/组件/"
  },
  {
    name: "v-75f01a3e",
    path: "/categories/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-75f01a3e").then(next)
    },
    meta: {"pid":"categories","id":"正则"}
  },
  {
    path: "/categories/正则/index.html",
    redirect: "/categories/正则/"
  },
  {
    path: "/categories/%E6%AD%A3%E5%88%99/",
    redirect: "/categories/正则/"
  },
  {
    name: "v-1b8d5889",
    path: "/categories/深夜食堂/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-1b8d5889").then(next)
    },
    meta: {"pid":"categories","id":"深夜食堂"}
  },
  {
    path: "/categories/深夜食堂/index.html",
    redirect: "/categories/深夜食堂/"
  },
  {
    path: "/categories/%E6%B7%B1%E5%A4%9C%E9%A3%9F%E5%A0%82/",
    redirect: "/categories/深夜食堂/"
  },
  {
    name: "v-7f71ddbe",
    path: "/tag/JS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f71ddbe").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/page/2/index.html",
    redirect: "/tag/JS/page/2/"
  },
  {
    name: "v-d6ece308",
    path: "/categories/前端小笔记/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6ece308").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/page/2/index.html",
    redirect: "/categories/前端小笔记/page/2/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/page/2/",
    redirect: "/categories/前端小笔记/page/2/"
  },
  {
    name: "v-d6ece2ca",
    path: "/categories/前端小笔记/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6ece2ca").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/page/3/index.html",
    redirect: "/categories/前端小笔记/page/3/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/page/3/",
    redirect: "/categories/前端小笔记/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]