/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "饭团也有春天",
  "description": "JabinPeng的博客",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "https://www.zpzpup.com/assets/image/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "script",
      {
        "src": "/blog/assets/js/bodyClick.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Nginx中文文件无法访问",
      "frontmatter": {
        "title": "Nginx中文文件无法访问",
        "date": "2018-11-12T00:00:00.000Z",
        "tags": [
          "Nginx"
        ],
        "categories": [
          "问题集中营"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180107.html",
      "relativePath": "blogs/category1/2018/20180107.md",
      "key": "v-f95dba00",
      "path": "/blogs/category1/2018/20180107.html",
      "headers": [
        {
          "level": 2,
          "title": "一.Nginx环境和服务器环境问题",
          "slug": "一-nginx环境和服务器环境问题"
        },
        {
          "level": 2,
          "title": "二.第二种情况大多数是上传的工具问题",
          "slug": "二-第二种情况大多数是上传的工具问题"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.97kb"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Peng Blog",
        "tagline": "一个被程序员生涯耽误的优秀厨子",
        "heroTextStyle": {
          "color": "#fff"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-21d6474e",
      "path": "/",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.34kb"
    },
    {
      "title": "屏幕适配函数,（例子：图表中适用很香）",
      "frontmatter": {
        "title": "屏幕适配函数,（例子：图表中适用很香）",
        "date": "2018-06-12T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180612.html",
      "relativePath": "blogs/category1/2018/20180612.md",
      "key": "v-3f6211c0",
      "path": "/blogs/category1/2018/20180612.html",
      "headers": [
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 2,
          "title": "1.获取屏幕宽高对象",
          "slug": "_1-获取屏幕宽高对象"
        },
        {
          "level": 2,
          "title": "2.根据设置的屏幕宽高计算出适合的宽高",
          "slug": "_2-根据设置的屏幕宽高计算出适合的宽高"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.84kb"
    },
    {
      "title": "下划线转驼峰",
      "frontmatter": {
        "title": "下划线转驼峰",
        "date": "2018-08-16T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180816.html",
      "relativePath": "blogs/category1/2018/20180816.md",
      "key": "v-17ae3340",
      "path": "/blogs/category1/2018/20180816.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.31kb"
    },
    {
      "title": "阻止浏览器默认事件",
      "frontmatter": {
        "title": "阻止浏览器默认事件",
        "date": "2018-09-21T00:00:00.000Z",
        "tags": [
          "HTML"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180921.html",
      "relativePath": "blogs/category1/2018/20180921.md",
      "key": "v-7f215b00",
      "path": "/blogs/category1/2018/20180921.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.27kb"
    },
    {
      "title": "随机生成数字",
      "frontmatter": {
        "title": "随机生成数字",
        "date": "2018-01-22T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180122.html",
      "relativePath": "blogs/category1/2018/20180122.md",
      "key": "v-b4672840",
      "path": "/blogs/category1/2018/20180122.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.76kb"
    },
    {
      "title": "生成随机字符串",
      "frontmatter": {
        "title": "生成随机字符串",
        "date": "2018-02-13T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180213.html",
      "relativePath": "blogs/category1/2018/20180213.md",
      "key": "v-4e013100",
      "path": "/blogs/category1/2018/20180213.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.49kb"
    },
    {
      "title": "深拷贝 & 浅拷贝",
      "frontmatter": {
        "title": "深拷贝 & 浅拷贝",
        "date": "2018-10-21T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20181021.html",
      "relativePath": "blogs/category1/2018/20181021.md",
      "key": "v-fb822f80",
      "path": "/blogs/category1/2018/20181021.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.77kb"
    },
    {
      "title": "强制横屏",
      "frontmatter": {
        "title": "强制横屏",
        "date": "2018-12-20T00:00:00.000Z",
        "tags": [
          "CSS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20181220.html",
      "relativePath": "blogs/category1/2018/20181220.md",
      "key": "v-bee86fc0",
      "path": "/blogs/category1/2018/20181220.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.63kb"
    },
    {
      "title": "CSS图片效果",
      "frontmatter": {
        "title": "CSS图片效果",
        "date": "2018-11-12T00:00:00.000Z",
        "tags": [
          "CSS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20181112.html",
      "relativePath": "blogs/category1/2018/20181112.md",
      "key": "v-951c3840",
      "path": "/blogs/category1/2018/20181112.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.30kb"
    },
    {
      "title": "阻止冒泡",
      "frontmatter": {
        "title": "阻止冒泡",
        "date": "2018-12-15T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20181215.html",
      "relativePath": "blogs/category1/2018/20181215.md",
      "key": "v-0a14ab60",
      "path": "/blogs/category1/2018/20181215.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.42kb"
    },
    {
      "title": "过滤对象中为空的属性",
      "frontmatter": {
        "title": "过滤对象中为空的属性",
        "date": "2019-03-30T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190330.html",
      "relativePath": "blogs/category1/2019/20190330.md",
      "key": "v-1aced800",
      "path": "/blogs/category1/2019/20190330.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.43kb"
    },
    {
      "title": "时间格式化",
      "frontmatter": {
        "title": "时间格式化",
        "date": "2019-02-16T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190216.html",
      "relativePath": "blogs/category1/2019/20190216.md",
      "key": "v-b35c79c0",
      "path": "/blogs/category1/2019/20190216.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.04kb"
    },
    {
      "title": "Cookie",
      "frontmatter": {
        "title": "Cookie",
        "date": "2019-01-24T00:00:00.000Z",
        "tags": [
          "Cookie"
        ],
        "categories": [
          "Cookie"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190124.html",
      "relativePath": "blogs/category1/2019/20190124.md",
      "key": "v-af2e10c0",
      "path": "/blogs/category1/2019/20190124.html",
      "headers": [
        {
          "level": 2,
          "title": "增",
          "slug": "增"
        },
        {
          "level": 2,
          "title": "删",
          "slug": "删"
        },
        {
          "level": 2,
          "title": "查",
          "slug": "查"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.79kb"
    },
    {
      "title": "bind",
      "frontmatter": {
        "title": "bind",
        "date": "2019-04-22T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190422.html",
      "relativePath": "blogs/category1/2019/20190422.md",
      "key": "v-1efd4100",
      "path": "/blogs/category1/2019/20190422.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.46kb"
    },
    {
      "title": "函数柯里化",
      "frontmatter": {
        "title": "函数柯里化",
        "date": "2019-05-23T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190523.html",
      "relativePath": "blogs/category1/2019/20190523.md",
      "key": "v-a08ef180",
      "path": "/blogs/category1/2019/20190523.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.37kb"
    },
    {
      "title": "排序",
      "frontmatter": {
        "title": "排序",
        "date": "2019-07-11T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "排序"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190711.html",
      "relativePath": "blogs/category1/2019/20190711.md",
      "key": "v-774b6b20",
      "path": "/blogs/category1/2019/20190711.html",
      "headers": [
        {
          "level": 2,
          "title": "冒泡排序",
          "slug": "冒泡排序"
        },
        {
          "level": 2,
          "title": "插入排序",
          "slug": "插入排序"
        },
        {
          "level": 2,
          "title": "快速排序",
          "slug": "快速排序"
        },
        {
          "level": 2,
          "title": "选择排序",
          "slug": "选择排序"
        },
        {
          "level": 2,
          "title": "归并排序",
          "slug": "归并排序"
        },
        {
          "level": 2,
          "title": "计数排序",
          "slug": "计数排序"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "3.40kb"
    },
    {
      "title": "滚动条操作",
      "frontmatter": {
        "title": "滚动条操作",
        "date": "2019-06-22T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190622.html",
      "relativePath": "blogs/category1/2019/20190622.md",
      "key": "v-4cf7e180",
      "path": "/blogs/category1/2019/20190622.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.00kb"
    },
    {
      "title": "内部监听生命周期函数",
      "frontmatter": {
        "title": "内部监听生命周期函数",
        "date": "2019-10-23T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2019/20191023.html",
      "relativePath": "blogs/category1/2019/20191023.md",
      "key": "v-f6491800",
      "path": "/blogs/category1/2019/20191023.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.28kb"
    },
    {
      "title": "加减乘除API",
      "frontmatter": {
        "title": "加减乘除API",
        "date": "2019-09-21T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190921.html",
      "relativePath": "blogs/category1/2019/20190921.md",
      "key": "v-275b7200",
      "path": "/blogs/category1/2019/20190921.html",
      "headers": [
        {
          "level": 2,
          "title": "1.加法运算",
          "slug": "_1-加法运算"
        },
        {
          "level": 2,
          "title": "2.减法运算",
          "slug": "_2-减法运算"
        },
        {
          "level": 2,
          "title": "3.乘法运算",
          "slug": "_3-乘法运算"
        },
        {
          "level": 2,
          "title": "4.除法运算",
          "slug": "_4-除法运算"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "3.03kb"
    },
    {
      "title": "Vue.extend",
      "frontmatter": {
        "title": "Vue.extend",
        "date": "2019-12-27T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2019/20191227.html",
      "relativePath": "blogs/category1/2019/20191227.md",
      "key": "v-ce953980",
      "path": "/blogs/category1/2019/20191227.html",
      "headers": [
        {
          "level": 2,
          "title": "开发loading组件",
          "slug": "开发loading组件"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.50kb"
    },
    {
      "title": "外部监听生命周期函数",
      "frontmatter": {
        "title": "外部监听生命周期函数",
        "date": "2019-11-20T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2019/20191120.html",
      "relativePath": "blogs/category1/2019/20191120.md",
      "key": "v-193b5c40",
      "path": "/blogs/category1/2019/20191120.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.67kb"
    },
    {
      "title": "Vue.extend(续)",
      "frontmatter": {
        "title": "Vue.extend(续)",
        "date": "2019-12-28T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2019/20191228.html",
      "relativePath": "blogs/category1/2019/20191228.md",
      "key": "v-636b3320",
      "path": "/blogs/category1/2019/20191228.html",
      "headers": [
        {
          "level": 2,
          "title": "通过Vue.extend将组件转换为全局组件",
          "slug": "通过vue-extend将组件转换为全局组件"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.01kb"
    },
    {
      "title": "Vue.observable",
      "frontmatter": {
        "title": "Vue.observable",
        "date": "2019-12-02T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2019/20191202.html",
      "relativePath": "blogs/category1/2019/20191202.md",
      "key": "v-e9c008c0",
      "path": "/blogs/category1/2019/20191202.html",
      "headers": [
        {
          "level": 2,
          "title": "创建store",
          "slug": "创建store"
        },
        {
          "level": 2,
          "title": "在组件中引用",
          "slug": "在组件中引用"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.75kb"
    },
    {
      "title": "call && apply",
      "frontmatter": {
        "title": "call && apply",
        "date": "2020-01-02T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200102.html",
      "relativePath": "blogs/category1/2020/20200102.md",
      "key": "v-5d2947a0",
      "path": "/blogs/category1/2020/20200102.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.54kb"
    },
    {
      "title": "Number处理",
      "frontmatter": {
        "title": "Number处理",
        "date": "2020-02-12T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200212.html",
      "relativePath": "blogs/category1/2020/20200212.md",
      "key": "v-44a268c0",
      "path": "/blogs/category1/2020/20200212.html",
      "headers": [
        {
          "level": 2,
          "title": "数字千分位分割",
          "slug": "数字千分位分割"
        },
        {
          "level": 2,
          "title": "生成随机数",
          "slug": "生成随机数"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.52kb"
    },
    {
      "title": "节流&防抖",
      "frontmatter": {
        "title": "节流&防抖",
        "date": "2020-03-16T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200316.html",
      "relativePath": "blogs/category1/2020/20200316.md",
      "key": "v-05f13a00",
      "path": "/blogs/category1/2020/20200316.html",
      "headers": [
        {
          "level": 2,
          "title": "函数节流 throttle",
          "slug": "函数节流-throttle"
        },
        {
          "level": 2,
          "title": "函数防抖 debounce",
          "slug": "函数防抖-debounce"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.77kb"
    },
    {
      "title": "过滤emoji表情",
      "frontmatter": {
        "title": "过滤emoji表情",
        "date": "2020-05-17T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200517.html",
      "relativePath": "blogs/category1/2020/20200517.md",
      "key": "v-9e803ac0",
      "path": "/blogs/category1/2020/20200517.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.36kb"
    },
    {
      "title": "Base64转blob对象",
      "frontmatter": {
        "title": "Base64转blob对象",
        "date": "2020-06-21T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200621.html",
      "relativePath": "blogs/category1/2020/20200621.md",
      "key": "v-71028760",
      "path": "/blogs/category1/2020/20200621.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.49kb"
    },
    {
      "title": "Promise",
      "frontmatter": {
        "title": "Promise",
        "date": "2020-04-22T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "Promise"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200422.html",
      "relativePath": "blogs/category1/2020/20200422.md",
      "key": "v-52b5a780",
      "path": "/blogs/category1/2020/20200422.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "5.32kb"
    },
    {
      "title": "CSS边框",
      "frontmatter": {
        "title": "CSS边框",
        "date": "2020-07-12T00:00:00.000Z",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2020/20200712.html",
      "relativePath": "blogs/category1/2020/20200712.md",
      "key": "v-b794fa00",
      "path": "/blogs/category1/2020/20200712.html",
      "headers": [
        {
          "level": 2,
          "title": "1.第一种单向变色",
          "slug": "_1-第一种单向变色"
        },
        {
          "level": 2,
          "title": "2.第二种双向渐变色",
          "slug": "_2-第二种双向渐变色"
        },
        {
          "level": 2,
          "title": "3.第三种中心展开变色",
          "slug": "_3-第三种中心展开变色"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.64kb"
    },
    {
      "title": "“&”运算符",
      "frontmatter": {
        "title": null,
        "date": "2020-07-23T00:00:00.000Z",
        "tags": [
          "运算符"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200723.html",
      "relativePath": "blogs/category1/2020/20200723.md",
      "key": "v-0a210200",
      "path": "/blogs/category1/2020/20200723.html",
      "headers": [
        {
          "level": 2,
          "title": "“&”运算符",
          "slug": "运算符"
        },
        {
          "level": 2,
          "title": "“|”运算符",
          "slug": "运算符-2"
        },
        {
          "level": 2,
          "title": "“^”运算符",
          "slug": "运算符-3"
        },
        {
          "level": 2,
          "title": "“~”运算符",
          "slug": "运算符-4"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.38kb"
    },
    {
      "title": "npm发布插件",
      "frontmatter": {
        "title": "npm发布插件",
        "date": "2020-08-22T00:00:00.000Z",
        "tags": [
          "npm"
        ],
        "categories": [
          "npm"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2020/20200822.html",
      "relativePath": "blogs/category1/2020/20200822.md",
      "key": "v-24bb0700",
      "path": "/blogs/category1/2020/20200822.html",
      "headers": [
        {
          "level": 2,
          "title": "1.首先我们先准备好需要发布的vue插件",
          "slug": "_1-首先我们先准备好需要发布的vue插件"
        },
        {
          "level": 2,
          "title": "2.当我们准备好了插件后，我们就需要登录npm官网",
          "slug": "_2-当我们准备好了插件后，我们就需要登录npm官网"
        },
        {
          "level": 2,
          "title": "3.注册完成登录后，咱们进行下一步",
          "slug": "_3-注册完成登录后，咱们进行下一步"
        },
        {
          "level": 2,
          "title": "4.咱们把插件放进文件目录中 就可以发布了",
          "slug": "_4-咱们把插件放进文件目录中-就可以发布了"
        },
        {
          "level": 2,
          "title": "5.当咱们发布完成后，可以到npm官网中查看",
          "slug": "_5-当咱们发布完成后，可以到npm官网中查看"
        },
        {
          "level": 2,
          "title": "6.最后大家可以体验自己发布的插件了",
          "slug": "_6-最后大家可以体验自己发布的插件了"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.00kb"
    },
    {
      "title": "Vue-watch",
      "frontmatter": {
        "title": "Vue-watch",
        "date": "2020-09-17T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200917.html",
      "relativePath": "blogs/category1/2020/20200917.md",
      "key": "v-fa757bc0",
      "path": "/blogs/category1/2020/20200917.html",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "立即触发",
          "slug": "立即触发"
        },
        {
          "level": 2,
          "title": "深度监听",
          "slug": "深度监听"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.81kb"
    },
    {
      "title": "函数式组件",
      "frontmatter": {
        "title": "函数式组件",
        "date": "2020-10-23T00:00:00.000Z",
        "tags": [
          "组件"
        ],
        "categories": [
          "组件"
        ]
      },
      "regularPath": "/blogs/category1/2020/20201023.html",
      "relativePath": "blogs/category1/2020/20201023.md",
      "key": "v-31e08800",
      "path": "/blogs/category1/2020/20201023.html",
      "headers": [
        {
          "level": 2,
          "title": "先来一个函数式组件的代码",
          "slug": "先来一个函数式组件的代码"
        },
        {
          "level": 2,
          "title": "为什么使用函数式组件",
          "slug": "为什么使用函数式组件"
        },
        {
          "level": 2,
          "title": "我不想用JSX，能用函数式组件吗？",
          "slug": "我不想用jsx，能用函数式组件吗？"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.58kb"
    },
    {
      "title": "vuepress 彩带插件",
      "frontmatter": {
        "title": "vuepress 彩带插件",
        "date": "2020-12-06T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2020/20201206.html",
      "relativePath": "blogs/category1/2020/20201206.md",
      "key": "v-182b8320",
      "path": "/blogs/category1/2020/20201206.html",
      "headers": [
        {
          "level": 2,
          "title": "💌 vuepress-plugin-sakura",
          "slug": "💌-vuepress-plugin-sakura"
        },
        {
          "level": 3,
          "title": "📎 项目配置也是很简单",
          "slug": "📎-项目配置也是很简单"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.26kb"
    },
    {
      "title": "vuepress 樱花插件",
      "frontmatter": {
        "title": "vuepress 樱花插件",
        "date": "2021-01-12T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2021/20210112.html",
      "relativePath": "blogs/category1/2021/20210112.md",
      "key": "v-565e5fc0",
      "path": "/blogs/category1/2021/20210112.html",
      "headers": [
        {
          "level": 2,
          "title": "💌 vuepress-plugin-sakura",
          "slug": "💌-vuepress-plugin-sakura"
        },
        {
          "level": 3,
          "title": "📎 项目配置也是很简单",
          "slug": "📎-项目配置也是很简单"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.66kb"
    },
    {
      "title": "多个props绑定和覆盖",
      "frontmatter": {
        "title": "多个props绑定和覆盖",
        "date": "2020-11-30T00:00:00.000Z",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/blogs/category1/2020/20201130.html",
      "relativePath": "blogs/category1/2020/20201130.md",
      "key": "v-0773d060",
      "path": "/blogs/category1/2020/20201130.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.89kb"
    },
    {
      "title": "npm 插件编写",
      "frontmatter": {
        "title": "npm 插件编写",
        "date": "2020-12-22T00:00:00.000Z",
        "tags": [
          "npm"
        ],
        "categories": [
          "npm"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2020/20201222.html",
      "relativePath": "blogs/category1/2020/20201222.md",
      "key": "v-055c9be0",
      "path": "/blogs/category1/2020/20201222.html",
      "headers": [
        {
          "level": 2,
          "title": "1.写好对应的vue组件",
          "slug": "_1-写好对应的vue组件"
        },
        {
          "level": 2,
          "title": "2.咱们封装好组件后需要导出一下",
          "slug": "_2-咱们封装好组件后需要导出一下"
        },
        {
          "level": 2,
          "title": "3.根据vuepress导出语法",
          "slug": "_3-根据vuepress导出语法"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "7.68kb"
    },
    {
      "title": "AsyncData",
      "frontmatter": {
        "title": "AsyncData",
        "date": "2021-07-08T00:00:00.000Z"
      },
      "regularPath": "/docs/Nuxt/asyncData.html",
      "relativePath": "docs/Nuxt/asyncData.md",
      "key": "v-0f7de0ad",
      "path": "/docs/Nuxt/asyncData.html",
      "headers": [
        {
          "level": 2,
          "title": "第一个参数",
          "slug": "第一个参数"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.45kb"
    },
    {
      "title": "保留小数",
      "frontmatter": {
        "title": "保留小数",
        "date": "2021-02-26T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2021/20210226.html",
      "relativePath": "blogs/category1/2021/20210226.md",
      "key": "v-01bb2340",
      "path": "/blogs/category1/2021/20210226.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.27kb"
    },
    {
      "title": "Nuxt",
      "frontmatter": {
        "title": "Nuxt",
        "date": "2021-07-08T00:00:00.000Z"
      },
      "regularPath": "/docs/Nuxt/introduction.html",
      "relativePath": "docs/Nuxt/introduction.md",
      "key": "v-01748fb5",
      "path": "/docs/Nuxt/introduction.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.49kb"
    },
    {
      "title": "全局API",
      "frontmatter": {
        "title": "全局API",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/API.html",
      "relativePath": "docs/Vue/API.md",
      "key": "v-23b9ead9",
      "path": "/docs/Vue/API.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        },
        {
          "level": 3,
          "title": "提供/注入 (Provide / Inject)",
          "slug": "提供-注入-provide-inject"
        },
        {
          "level": 3,
          "title": "工厂",
          "slug": "工厂"
        },
        {
          "level": 3,
          "title": "nextTick",
          "slug": "nexttick"
        },
        {
          "level": 3,
          "title": "v-if v-else v-else-if",
          "slug": "v-if-v-else-v-else-if"
        },
        {
          "level": 3,
          "title": "",
          "slug": "template-v-for"
        },
        {
          "level": 3,
          "title": "按键修饰符",
          "slug": "按键修饰符"
        },
        {
          "level": 3,
          "title": "在 prop 的默认函数中访问 this",
          "slug": "在-prop-的默认函数中访问-this"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "3.54kb"
    },
    {
      "title": "常用正则表达式",
      "frontmatter": {
        "title": "常用正则表达式",
        "date": "2021-01-22T00:00:00.000Z",
        "tags": [
          "正则"
        ],
        "categories": [
          "正则"
        ]
      },
      "regularPath": "/blogs/category1/2021/20210122.html",
      "relativePath": "blogs/category1/2021/20210122.md",
      "key": "v-3b3ae840",
      "path": "/blogs/category1/2021/20210122.html",
      "headers": [
        {
          "level": 2,
          "title": "1.校验数字的表达式",
          "slug": "_1-校验数字的表达式"
        },
        {
          "level": 2,
          "title": "2.校验字符的表达式",
          "slug": "_2-校验字符的表达式"
        },
        {
          "level": 2,
          "title": "3.特殊需求表达式",
          "slug": "_3-特殊需求表达式"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "4.34kb"
    },
    {
      "title": "Data",
      "frontmatter": {
        "title": "Data",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/Data.html",
      "relativePath": "docs/Vue/Data.md",
      "key": "v-73f27207",
      "path": "/docs/Vue/Data.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        },
        {
          "level": 2,
          "title": "Mixin 合并行为变更",
          "slug": "mixin-合并行为变更"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.12kb"
    },
    {
      "title": "异步组件",
      "frontmatter": {
        "title": "异步组件",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/asyncComponent.html",
      "relativePath": "docs/Vue/asyncComponent.md",
      "key": "v-16a30127",
      "path": "/docs/Vue/asyncComponent.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.12kb"
    },
    {
      "title": "Context",
      "frontmatter": {
        "title": "Context",
        "date": "2021-07-08T00:00:00.000Z"
      },
      "regularPath": "/docs/Nuxt/context.html",
      "relativePath": "docs/Nuxt/context.md",
      "key": "v-45a4bc0d",
      "path": "/docs/Nuxt/context.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.10kb"
    },
    {
      "title": "attribute 强制行为",
      "frontmatter": {
        "title": "attribute 强制行为",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/attribute.html",
      "relativePath": "docs/Vue/attribute.md",
      "key": "v-1ad07d56",
      "path": "/docs/Vue/attribute.html",
      "headers": [
        {
          "level": 2,
          "title": "布尔属性",
          "slug": "布尔属性"
        },
        {
          "level": 2,
          "title": "枚举属性",
          "slug": "枚举属性"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.97kb"
    },
    {
      "title": "过渡class变化",
      "frontmatter": {
        "title": "过渡class变化",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/animationClass.html",
      "relativePath": "docs/Vue/animationClass.md",
      "key": "v-7b37f5f2",
      "path": "/docs/Vue/animationClass.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.48kb"
    },
    {
      "title": "directive 指令",
      "frontmatter": {
        "title": "directive 指令",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/directive.html",
      "relativePath": "docs/Vue/directive.md",
      "key": "v-c63ab422",
      "path": "/docs/Vue/directive.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.26kb"
    },
    {
      "title": "Event",
      "frontmatter": {
        "title": "Event",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/event.html",
      "relativePath": "docs/Vue/event.md",
      "key": "v-0d2706d9",
      "path": "/docs/Vue/event.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.92kb"
    },
    {
      "title": "函数式组件",
      "frontmatter": {
        "title": "函数式组件",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/funComponent.html",
      "relativePath": "docs/Vue/funComponent.md",
      "key": "v-63d8ae87",
      "path": "/docs/Vue/funComponent.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.91kb"
    },
    {
      "title": "Ref区别",
      "frontmatter": {
        "title": "Ref区别",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/ref.html",
      "relativePath": "docs/Vue/ref.md",
      "key": "v-1db6f6e7",
      "path": "/docs/Vue/ref.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.63kb"
    },
    {
      "title": "filters",
      "frontmatter": {
        "title": "filters",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/filters.html",
      "relativePath": "docs/Vue/filters.md",
      "key": "v-9f5475d2",
      "path": "/docs/Vue/filters.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.79kb"
    },
    {
      "title": "片段",
      "frontmatter": {
        "title": "片段",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/template.html",
      "relativePath": "docs/Vue/template.md",
      "key": "v-18ea60f2",
      "path": "/docs/Vue/template.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.44kb"
    },
    {
      "title": "slot统一",
      "frontmatter": {
        "title": "slot统一",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/slot.html",
      "relativePath": "docs/Vue/slot.md",
      "key": "v-548658f2",
      "path": "/docs/Vue/slot.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.62kb"
    },
    {
      "title": "v-if 与 v-for 的优先级对比",
      "frontmatter": {
        "title": "v-if 与 v-for 的优先级对比",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-if&v-for.html",
      "relativePath": "docs/Vue/v-if&v-for.md",
      "key": "v-d1cc67f2",
      "path": "/docs/Vue/v-if&v-for.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.20kb"
    },
    {
      "title": "渲染函数",
      "frontmatter": {
        "title": "渲染函数",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/renderFun.html",
      "relativePath": "docs/Vue/renderFun.md",
      "key": "v-5abaae7b",
      "path": "/docs/Vue/renderFun.html",
      "headers": [
        {
          "level": 3,
          "title": "渲染函数参数Props",
          "slug": "渲染函数参数props"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.07kb"
    },
    {
      "title": "v-bind",
      "frontmatter": {
        "title": "v-bind",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-bind.html",
      "relativePath": "docs/Vue/v-bind.md",
      "key": "v-16d28407",
      "path": "/docs/Vue/v-bind.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.57kb"
    },
    {
      "title": "无油捞汁粉丝",
      "frontmatter": {
        "title": "无油捞汁粉丝",
        "date": "2021-06-18T00:00:00.000Z",
        "categories": "深夜食堂"
      },
      "regularPath": "/docs/delicacys/%E6%97%A0%E6%B2%B9%E6%8D%9E%E6%B1%81%E7%B2%89%E4%B8%9D.html",
      "relativePath": "docs/delicacys/无油捞汁粉丝.md",
      "key": "v-4dfc2596",
      "path": "/docs/delicacys/%E6%97%A0%E6%B2%B9%E6%8D%9E%E6%B1%81%E7%B2%89%E4%B8%9D.html",
      "headers": [
        {
          "level": 3,
          "title": "祝你拥有清爽而值得回味的夏天🍃",
          "slug": "祝你拥有清爽而值得回味的夏天🍃"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.26kb"
    },
    {
      "title": "v-model",
      "frontmatter": {
        "title": "v-model",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-model.html",
      "relativePath": "docs/Vue/v-model.md",
      "key": "v-18f77d29",
      "path": "/docs/Vue/v-model.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2. x",
          "slug": "vue2-x"
        },
        {
          "level": 2,
          "title": "vue3. x",
          "slug": "vue3-x"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.21kb"
    },
    {
      "title": "v-is",
      "frontmatter": {
        "title": "v-is",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-is.html",
      "relativePath": "docs/Vue/v-is.md",
      "key": "v-0e73ed27",
      "path": "/docs/Vue/v-is.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.37kb"
    },
    {
      "title": "DOM操作",
      "frontmatter": {
        "title": "DOM操作",
        "date": "2021-01-12T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/DOM.html",
      "relativePath": "docs/jottings/DOM.md",
      "key": "v-25cf21cd",
      "path": "/docs/jottings/DOM.html",
      "headers": [
        {
          "level": 2,
          "title": "固定滚动条",
          "slug": "固定滚动条"
        },
        {
          "level": 2,
          "title": "判断当前位置是否为页面底部",
          "slug": "判断当前位置是否为页面底部"
        },
        {
          "level": 2,
          "title": "判断元素是否在可视范围内",
          "slug": "判断元素是否在可视范围内"
        },
        {
          "level": 2,
          "title": "获取元素css样式",
          "slug": "获取元素css样式"
        },
        {
          "level": 2,
          "title": "进入全屏",
          "slug": "进入全屏"
        },
        {
          "level": 2,
          "title": "退出全屏",
          "slug": "退出全屏"
        },
        {
          "level": 2,
          "title": "全屏事件",
          "slug": "全屏事件"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.62kb"
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2021-02-22T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/Git.html",
      "relativePath": "docs/jottings/Git.md",
      "key": "v-a834b066",
      "path": "/docs/jottings/Git.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "Git 相关",
          "slug": "git-相关"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "5.24kb"
    },
    {
      "title": "BOM对象",
      "frontmatter": {
        "title": "BOM对象",
        "date": "2021-01-20T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/BOM.html",
      "relativePath": "docs/jottings/BOM.md",
      "key": "v-036cff0d",
      "path": "/docs/jottings/BOM.html",
      "headers": [
        {
          "level": 2,
          "title": "判读浏览器是否支持 CSS 属性",
          "slug": "判读浏览器是否支持-css-属性"
        },
        {
          "level": 2,
          "title": "返回当前网页地址",
          "slug": "返回当前网页地址"
        },
        {
          "level": 2,
          "title": "获取滚动条位置",
          "slug": "获取滚动条位置"
        },
        {
          "level": 2,
          "title": "获取url中的参数",
          "slug": "获取url中的参数"
        },
        {
          "level": 2,
          "title": "页面跳转，是否记录在history中",
          "slug": "页面跳转，是否记录在history中"
        },
        {
          "level": 2,
          "title": "滚动条滚动到指定位置",
          "slug": "滚动条滚动到指定位置"
        },
        {
          "level": 2,
          "title": "复制文本",
          "slug": "复制文本"
        },
        {
          "level": 2,
          "title": "检测设备类型",
          "slug": "检测设备类型"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "4.91kb"
    },
    {
      "title": "HarmonyOS",
      "frontmatter": {
        "title": "HarmonyOS",
        "date": "2020-12-07T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/HarmonyOS.html",
      "relativePath": "docs/jottings/HarmonyOS.md",
      "key": "v-0cc8b28d",
      "path": "/docs/jottings/HarmonyOS.html",
      "headers": [
        {
          "level": 2,
          "title": "1.华为鸿蒙OS",
          "slug": "_1-华为鸿蒙os"
        },
        {
          "level": 2,
          "title": "2.下载鸿蒙编辑器Deveco-Studio",
          "slug": "_2-下载鸿蒙编辑器deveco-studio"
        },
        {
          "level": 2,
          "title": "3.启动编辑器",
          "slug": "_3-启动编辑器"
        },
        {
          "level": 2,
          "title": "3.创建一个项目",
          "slug": "_3-创建一个项目"
        },
        {
          "level": 2,
          "title": "4.登录华为账号",
          "slug": "_4-登录华为账号"
        },
        {
          "level": 2,
          "title": "5.项目启动",
          "slug": "_5-项目启动"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.13kb"
    },
    {
      "title": "CentOS7安装Nginx",
      "frontmatter": {
        "title": "CentOS7安装Nginx",
        "date": "2020-09-21T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/Nginx.html",
      "relativePath": "docs/jottings/Nginx.md",
      "key": "v-7c41320d",
      "path": "/docs/jottings/Nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "1.下载Nginx安装包",
          "slug": "_1-下载nginx安装包"
        },
        {
          "level": 2,
          "title": "2.解压",
          "slug": "_2-解压"
        },
        {
          "level": 2,
          "title": "3.配置",
          "slug": "_3-配置"
        },
        {
          "level": 2,
          "title": "4.编译安装",
          "slug": "_4-编译安装"
        },
        {
          "level": 2,
          "title": "5.开机自动启动",
          "slug": "_5-开机自动启动"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.93kb"
    },
    {
      "title": "手风琴",
      "frontmatter": {
        "title": "手风琴",
        "date": "2020-08-12T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/accordion.html",
      "relativePath": "docs/jottings/accordion.md",
      "key": "v-c019ed66",
      "path": "/docs/jottings/accordion.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "1.34kb"
    },
    {
      "title": "族谱",
      "frontmatter": {
        "title": "族谱",
        "date": "2020-12-22T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/genealogy.html",
      "relativePath": "docs/jottings/genealogy.md",
      "key": "v-c80c1626",
      "path": "/docs/jottings/genealogy.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.20kb"
    },
    {
      "title": "flex布局",
      "frontmatter": {
        "title": "flex布局",
        "date": "2020-11-06T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/flexbox.html",
      "relativePath": "docs/jottings/flexbox.md",
      "key": "v-40b05a4d",
      "path": "/docs/jottings/flexbox.html",
      "headers": [
        {
          "level": 2,
          "title": "live demo",
          "slug": "live-demo"
        },
        {
          "level": 2,
          "title": "属性解释",
          "slug": "属性解释"
        },
        {
          "level": 3,
          "title": "flexbox",
          "slug": "flexbox"
        },
        {
          "level": 3,
          "title": "flex-direction",
          "slug": "flex-direction"
        },
        {
          "level": 3,
          "title": "flex-wrap",
          "slug": "flex-wrap"
        },
        {
          "level": 3,
          "title": "flex-flow",
          "slug": "flex-flow"
        },
        {
          "level": 3,
          "title": "justify-content",
          "slug": "justify-content"
        },
        {
          "level": 3,
          "title": "align-items",
          "slug": "align-items"
        },
        {
          "level": 3,
          "title": "align-content",
          "slug": "align-content"
        },
        {
          "level": 3,
          "title": "order",
          "slug": "order"
        },
        {
          "level": 3,
          "title": "flex-basis",
          "slug": "flex-basis"
        },
        {
          "level": 3,
          "title": "flex-grow",
          "slug": "flex-grow"
        },
        {
          "level": 3,
          "title": "flex-shrink",
          "slug": "flex-shrink"
        },
        {
          "level": 3,
          "title": "align-self",
          "slug": "align-self"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.98kb"
    },
    {
      "title": "滤镜 filter",
      "frontmatter": {
        "title": "滤镜 filter",
        "date": "2020-05-29T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/filter.html",
      "relativePath": "docs/jottings/filter.md",
      "key": "v-5872dd42",
      "path": "/docs/jottings/filter.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.06kb"
    },
    {
      "title": "loading 加载动画",
      "frontmatter": {
        "title": "loading 加载动画",
        "date": "2020-09-15T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/loading.html",
      "relativePath": "docs/jottings/loading.md",
      "key": "v-4258630d",
      "path": "/docs/jottings/loading.html",
      "headers": [
        {
          "level": 2,
          "title": "loading_2",
          "slug": "loading-2"
        },
        {
          "level": 2,
          "title": "loading_3",
          "slug": "loading-3"
        },
        {
          "level": 2,
          "title": "loading_4",
          "slug": "loading-4"
        },
        {
          "level": 2,
          "title": "loading_5",
          "slug": "loading-5"
        },
        {
          "level": 2,
          "title": "loading_6",
          "slug": "loading-6"
        },
        {
          "level": 2,
          "title": "loading_7",
          "slug": "loading-7"
        },
        {
          "level": 2,
          "title": "相关项目",
          "slug": "相关项目"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "10.75kb"
    },
    {
      "title": "霓虹灯六角形粒子动画",
      "frontmatter": {
        "title": "霓虹灯六角形粒子动画",
        "date": "2020-12-25T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/particles.html",
      "relativePath": "docs/jottings/particles.md",
      "key": "v-85606726",
      "path": "/docs/jottings/particles.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "3.89kb"
    },
    {
      "title": "reset",
      "frontmatter": {
        "title": "reset",
        "date": "2020-05-28T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/reset.html",
      "relativePath": "docs/jottings/reset.md",
      "key": "v-bcaea4a6",
      "path": "/docs/jottings/reset.html",
      "headers": [
        {
          "level": 2,
          "title": "reset",
          "slug": "reset"
        },
        {
          "level": 2,
          "title": "去除input默认填充的背景颜色",
          "slug": "去除input默认填充的背景颜色"
        },
        {
          "level": 2,
          "title": "清除input[type=number]的默认样式",
          "slug": "清除input-type-number-的默认样式"
        },
        {
          "level": 2,
          "title": "清除移动端 a 标签等点击区域变色",
          "slug": "清除移动端-a-标签等点击区域变色"
        },
        {
          "level": 2,
          "title": "清除移动端 input 样式",
          "slug": "清除移动端-input-样式"
        },
        {
          "level": 2,
          "title": "避免ios滑动滚动条卡顿",
          "slug": "避免ios滑动滚动条卡顿"
        },
        {
          "level": 2,
          "title": "一次搞定",
          "slug": "一次搞定"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "3.44kb"
    },
    {
      "title": "滚动条样式",
      "frontmatter": {
        "title": "滚动条样式",
        "date": "2019-06-21T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/scrollTemp.html",
      "relativePath": "docs/jottings/scrollTemp.md",
      "key": "v-5248d10d",
      "path": "/docs/jottings/scrollTemp.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "0.76kb"
    },
    {
      "title": "移动端踩坑指南",
      "frontmatter": {
        "title": "移动端踩坑指南",
        "date": "2021-01-28T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/mobile.html",
      "relativePath": "docs/jottings/mobile.md",
      "key": "v-83700cea",
      "path": "/docs/jottings/mobile.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML方向",
          "slug": "html方向"
        },
        {
          "level": 3,
          "title": "调用系统功能",
          "slug": "调用系统功能"
        },
        {
          "level": 3,
          "title": "忽略自动识别",
          "slug": "忽略自动识别"
        },
        {
          "level": 3,
          "title": "弹出数字键盘",
          "slug": "弹出数字键盘"
        },
        {
          "level": 3,
          "title": "唤醒原生应用",
          "slug": "唤醒原生应用"
        },
        {
          "level": 3,
          "title": "禁止页面缩放",
          "slug": "禁止页面缩放"
        },
        {
          "level": 3,
          "title": "禁止页面缓存",
          "slug": "禁止页面缓存"
        },
        {
          "level": 3,
          "title": "禁止字母大写",
          "slug": "禁止字母大写"
        },
        {
          "level": 3,
          "title": "针对Safari配置",
          "slug": "针对safari配置"
        },
        {
          "level": 3,
          "title": "针对其他浏览器配置",
          "slug": "针对其他浏览器配置"
        },
        {
          "level": 3,
          "title": "让:active有效，让:hover无效",
          "slug": "让-active有效，让-hover无效"
        },
        {
          "level": 2,
          "title": "CSS方向",
          "slug": "css方向"
        },
        {
          "level": 3,
          "title": "自动适应布局",
          "slug": "自动适应布局"
        },
        {
          "level": 3,
          "title": "自动适应背景",
          "slug": "自动适应背景"
        },
        {
          "level": 3,
          "title": "监听屏幕旋转",
          "slug": "监听屏幕旋转"
        },
        {
          "level": 3,
          "title": "支持弹性滚动",
          "slug": "支持弹性滚动"
        },
        {
          "level": 3,
          "title": "禁止滚动传播",
          "slug": "禁止滚动传播"
        },
        {
          "level": 3,
          "title": "禁止屏幕抖动",
          "slug": "禁止屏幕抖动"
        },
        {
          "level": 3,
          "title": "禁止长按操作",
          "slug": "禁止长按操作"
        },
        {
          "level": 3,
          "title": "禁止字体调整",
          "slug": "禁止字体调整"
        },
        {
          "level": 3,
          "title": "禁止高亮显示",
          "slug": "禁止高亮显示"
        },
        {
          "level": 3,
          "title": "禁止动画闪屏",
          "slug": "禁止动画闪屏"
        },
        {
          "level": 3,
          "title": "美化表单外观",
          "slug": "美化表单外观"
        },
        {
          "level": 3,
          "title": "美化滚动占位",
          "slug": "美化滚动占位"
        },
        {
          "level": 3,
          "title": "美化输入占位",
          "slug": "美化输入占位"
        },
        {
          "level": 3,
          "title": "对齐输入占位",
          "slug": "对齐输入占位"
        },
        {
          "level": 3,
          "title": "对齐下拉选项",
          "slug": "对齐下拉选项"
        },
        {
          "level": 3,
          "title": "修复点击无效",
          "slug": "修复点击无效"
        },
        {
          "level": 3,
          "title": "识别文本换行",
          "slug": "识别文本换行"
        },
        {
          "level": 3,
          "title": "开启硬件加速",
          "slug": "开启硬件加速"
        },
        {
          "level": 3,
          "title": "描绘像素边框",
          "slug": "描绘像素边框"
        },
        {
          "level": 3,
          "title": "控制溢出文本",
          "slug": "控制溢出文本"
        },
        {
          "level": 2,
          "title": "JS方向",
          "slug": "js方向"
        },
        {
          "level": 3,
          "title": "禁止点击穿透",
          "slug": "禁止点击穿透"
        },
        {
          "level": 3,
          "title": "禁止滑动穿透",
          "slug": "禁止滑动穿透"
        },
        {
          "level": 3,
          "title": "支持往返刷新",
          "slug": "支持往返刷新"
        },
        {
          "level": 3,
          "title": "解析有效日期",
          "slug": "解析有效日期"
        },
        {
          "level": 3,
          "title": "修复输入监听",
          "slug": "修复输入监听"
        },
        {
          "level": 3,
          "title": "简化回到顶部",
          "slug": "简化回到顶部"
        },
        {
          "level": 3,
          "title": "简化懒性加载",
          "slug": "简化懒性加载"
        },
        {
          "level": 3,
          "title": "优化扫码识别",
          "slug": "优化扫码识别"
        },
        {
          "level": 3,
          "title": "自动播放媒体",
          "slug": "自动播放媒体"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "15.80kb"
    },
    {
      "title": "常见阴影",
      "frontmatter": {
        "title": "常见阴影",
        "date": "2019-06-21T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/shadow.html",
      "relativePath": "docs/jottings/shadow.md",
      "key": "v-dea57fe2",
      "path": "/docs/jottings/shadow.html",
      "headers": [
        {
          "level": 2,
          "title": "常见投影",
          "slug": "常见投影"
        },
        {
          "level": 2,
          "title": "不规则图形投影",
          "slug": "不规则图形投影"
        }
      ],
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "2.30kb"
    },
    {
      "title": "旋转木马",
      "frontmatter": {
        "title": "旋转木马",
        "date": "2020-12-24T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/whirligig.html",
      "relativePath": "docs/jottings/whirligig.md",
      "key": "v-763b410d",
      "path": "/docs/jottings/whirligig.html",
      "lastUpdated": "2021/11/16 下午5:58:25",
      "size": "6.76kb"
    },
    {
      "title": "关于 Vue 项目打包部署知识点总结",
      "frontmatter": {
        "title": "关于 Vue 项目打包部署知识点总结",
        "date": "2021-11-16T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/vueBuild.html",
      "relativePath": "docs/jottings/vueBuild.md",
      "key": "v-dabf3b02",
      "path": "/docs/jottings/vueBuild.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 准备一台服务器",
          "slug": "_1-准备一台服务器"
        },
        {
          "level": 2,
          "title": "2. nginx安装和启动",
          "slug": "_2-nginx安装和启动"
        },
        {
          "level": 2,
          "title": "3、 了解nginx: 修改nginx配置，让nginx服务器代理我们创建的文件",
          "slug": "_3、-了解nginx-修改nginx配置，让nginx服务器代理我们创建的文件"
        },
        {
          "level": 3,
          "title": "1、创建文件夹/www，并创建index.html，写入\"Hello world\"字符串",
          "slug": "_1、创建文件夹-www，并创建index-html，写入-hello-world-字符串"
        },
        {
          "level": 3,
          "title": "2、修改root值为 /www",
          "slug": "_2、修改root值为-www"
        },
        {
          "level": 3,
          "title": "3、sudo nginx -t 检查nginx配置是否正确",
          "slug": "_3、sudo-nginx-t-检查nginx配置是否正确"
        },
        {
          "level": 3,
          "title": "4、加载nginx配置：sudo nginx -s reload",
          "slug": "_4、加载nginx配置：sudo-nginx-s-reload"
        }
      ],
      "lastUpdated": "2021/11/20 上午10:48:46",
      "size": "1.72kb"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Nginx Tags"
      },
      "regularPath": "/tag/Nginx/",
      "key": "v-dab8e1c2",
      "path": "/tag/Nginx/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JS Tags"
      },
      "regularPath": "/tag/JS/",
      "key": "v-e8d965c8",
      "path": "/tag/JS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "HTML Tags"
      },
      "regularPath": "/tag/HTML/",
      "key": "v-184d950c",
      "path": "/tag/HTML/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS Tags"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Cookie Tags"
      },
      "regularPath": "/tag/Cookie/",
      "key": "v-ec38e77e",
      "path": "/tag/Cookie/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "VUE Tags"
      },
      "regularPath": "/tag/VUE/",
      "key": "v-3248559a",
      "path": "/tag/VUE/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "运算符 Tags"
      },
      "regularPath": "/tag/%E8%BF%90%E7%AE%97%E7%AC%A6/",
      "key": "v-7c44ce15",
      "path": "/tag/运算符/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "npm Tags"
      },
      "regularPath": "/tag/npm/",
      "key": "v-3231af64",
      "path": "/tag/npm/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "组件 Tags"
      },
      "regularPath": "/tag/%E7%BB%84%E4%BB%B6/",
      "key": "v-4bc4e1e0",
      "path": "/tag/组件/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "正则 Tags"
      },
      "regularPath": "/tag/%E6%AD%A3%E5%88%99/",
      "key": "v-0c1cbc56",
      "path": "/tag/正则/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "问题集中营 Categories"
      },
      "regularPath": "/categories/%E9%97%AE%E9%A2%98%E9%9B%86%E4%B8%AD%E8%90%A5/",
      "key": "v-1f2f3733",
      "path": "/categories/问题集中营/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端小笔记 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
      "key": "v-d2055fbe",
      "path": "/categories/前端小笔记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Cookie Categories"
      },
      "regularPath": "/categories/Cookie/",
      "key": "v-d0fbe166",
      "path": "/categories/Cookie/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "排序 Categories"
      },
      "regularPath": "/categories/%E6%8E%92%E5%BA%8F/",
      "key": "v-85672be2",
      "path": "/categories/排序/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "VUE Categories"
      },
      "regularPath": "/categories/VUE/",
      "key": "v-7f070da7",
      "path": "/categories/VUE/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Promise Categories"
      },
      "regularPath": "/categories/Promise/",
      "key": "v-3dfe3db2",
      "path": "/categories/Promise/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "CSS Categories"
      },
      "regularPath": "/categories/CSS/",
      "key": "v-7efe64ca",
      "path": "/categories/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "npm Categories"
      },
      "regularPath": "/categories/npm/",
      "key": "v-7f1260c2",
      "path": "/categories/npm/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "组件 Categories"
      },
      "regularPath": "/categories/%E7%BB%84%E4%BB%B6/",
      "key": "v-b5983fc8",
      "path": "/categories/组件/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "正则 Categories"
      },
      "regularPath": "/categories/%E6%AD%A3%E5%88%99/",
      "key": "v-75f01a3e",
      "path": "/categories/正则/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "深夜食堂 Categories"
      },
      "regularPath": "/categories/%E6%B7%B1%E5%A4%9C%E9%A3%9F%E5%A0%82/",
      "key": "v-1b8d5889",
      "path": "/categories/深夜食堂/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - JS | Tags"
      },
      "regularPath": "/tag/JS/page/2/",
      "key": "v-7f71ddbe",
      "path": "/tag/JS/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - 前端小笔记 | Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/page/2/",
      "key": "v-d6ece308",
      "path": "/categories/前端小笔记/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 3 - 前端小笔记 | Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/page/3/",
      "key": "v-d6ece2ca",
      "path": "/categories/前端小笔记/page/3/"
    }
  ],
  "themeConfig": {
    "mode": "dark",
    "noFoundPageByTencent": true,
    "logo": "https://www.zpzpup.com/assets/image/avatar.png",
    "valineConfig": {
      "appId": "e6ojaBbYmQvJLNWeBouhonP6-gzGzoHsz",
      "appKey": "050ScrJoJUW37QqwVwzSmKoX"
    },
    "nav": [
      {
        "text": "随意一点的主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "莫名其妙的时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "很厉害的文章",
        "icon": "reco-document",
        "items": [
          {
            "text": "七杂八杂",
            "link": "/docs/jottings/mobile"
          },
          {
            "text": "Vue3.0",
            "link": "/docs/vue/ref"
          },
          {
            "text": "Nuxt",
            "link": "/docs/nuxt/introduction"
          },
          {
            "text": "吃吃吃",
            "link": "/docs/delicacys/无油捞汁粉丝"
          }
        ]
      },
      {
        "text": "联系我吧",
        "icon": "reco-message",
        "items": [
          {
            "text": "Me",
            "link": "https://www.zpzpup.com"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/JabinPeng",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/jottings/": [
        "mobile",
        "Git",
        "HarmonyOS",
        "DOM",
        "BOM",
        "particles",
        "whirligig",
        "filter",
        "scrollTemp",
        "reset",
        "Nginx",
        "accordion",
        "loading",
        "shadow",
        "flexbox"
      ],
      "/docs/Vue/": [
        {
          "title": "Vue3.0",
          "collapsable": false,
          "children": [
            "ref",
            "asyncComponent",
            "attribute",
            "directive",
            "v-is",
            "Data",
            "event",
            "filters",
            "template",
            "funComponent",
            "API",
            "renderFun",
            "slot",
            "animationClass",
            "v-model",
            "v-if&v-for",
            "v-bind"
          ]
        }
      ],
      "/docs/Nuxt/": [
        {
          "title": "Nuxt",
          "collapsable": false,
          "children": [
            "introduction",
            "asyncData",
            "context"
          ]
        }
      ]
    },
    "type": "blog",
    "blogConfig": {
      "tag": {
        "location": 3,
        "text": "无关紧要的小标签"
      }
    },
    "friendLink": [
      {
        "title": "Lucifer",
        "desc": "Everything can be expected in the future.",
        "email": "2050180797@qq.com",
        "logo": "https://nightliuguoxing-github-io.vercel.app/img/avatar.jpg",
        "link": "https://love.liuguoxing.top"
      },
      {
        "title": "午后南杂",
        "desc": "一款简洁而优雅的 vuepress 博客 & 文档 主题。",
        "email": "无",
        "link": "https://vuepress-theme-reco.recoluan.com/"
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "Jabin",
    "authorAvatar": "https://www.zpzpup.com/assets/image/avatar.png",
    "record": "鄂ICP备18004957号",
    "startYear": "2018"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}